config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  devise_for :users
  resources :envfiles
  resources :namespaces
  resources :teams, only: [:index]
  resources :applications, only: [:index]
  resources :environments, only: [:index]

  match "*path", to: "application#index", format: false, via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/envfile.rb
# == Schema Information
#
# Table name: envfiles
#
#  id           :bigint           not null, primary key
#  filename     :string(255)      not null
#  namespace_id :bigint           not null
#  filetype     :integer          default(0)
#  deleted_at   :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Envfile < ApplicationRecord
  has_one_attached :file

  belongs_to :namespace, counter_cache: true
end

app/models/namespace.rb
# == Schema Information
#
# Table name: namespaces
#
#  id             :bigint           not null, primary key
#  team           :string(255)      not null
#  application    :string(255)      not null
#  environment    :string(255)      not null
#  deleted_at     :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  envfiles_count :integer
#

# TODO: exteract team to create team specific settings
class Namespace < ApplicationRecord
  has_many :envfiles

  before_save do
    self.environment = environment.gsub(' ', '').underscore
    self.team = team.gsub(' ', '').underscore
    self.application = application.gsub(' ', '').underscore
  end

  def pathname
    [
      environment,
      team,
      application
    ].join('/')
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :bigint           not null, primary key
#  username            :string(255)      not null
#  email               :string(255)
#  encrypted_password  :string(255)
#  remember_created_at :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable, :rememberable

  before_save { self.username = username.downcase }

  validates :username, uniqueness: true

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def password_required?
    false
  end

  def password_changed?
    false
  end

  # use this instead of email_changed? for Rails = 5.1.x
  def will_save_change_to_email?
    false
  end

  def will_save_change_to_password?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  before_action :authenticate_user!

  def index
    @namespaces = Namespace.all
    render template: 'application'
  end

  private

  def layout_by_resource
    if devise_controller?
      'default'
    else
      'application'
    end
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    render json: {
      results: Namespace.distinct(:application).pluck(:application).map do |application|
        {
          name: application,
          value: application,
          text: application,
          disabled: false
        }
      end
    }
  end
end

app/controllers/envfiles_controller.rb
class EnvfilesController < ApplicationController
  before_action :set_envfile, only: [:show, :edit, :update, :destroy]

  # GET /envfiles
  # GET /envfiles.json
  def index
    @envfiles = Envfile.all
  end

  # GET /envfiles/1
  # GET /envfiles/1.json
  def show
  end

  # GET /envfiles/new
  def new
    @envfile = Envfile.new
  end

  # GET /envfiles/1/edit
  def edit
  end

  # POST /envfiles
  # POST /envfiles.json
  def create
    @envfile = Envfile.new(envfile_params)

    respond_to do |format|
      if @envfile.save
        format.html { redirect_to @envfile, notice: 'Envfile was successfully created.' }
        format.json { render :show, status: :created, location: @envfile }
      else
        format.html { render :new }
        format.json { render json: @envfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /envfiles/1
  # PATCH/PUT /envfiles/1.json
  def update
    respond_to do |format|
      if @envfile.update(envfile_params)
        format.html { redirect_to @envfile, notice: 'Envfile was successfully updated.' }
        format.json { render :show, status: :ok, location: @envfile }
      else
        format.html { render :edit }
        format.json { render json: @envfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /envfiles/1
  # DELETE /envfiles/1.json
  def destroy
    @envfile.destroy
    respond_to do |format|
      format.html { redirect_to envfiles_url, notice: 'Envfile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_envfile
      @envfile = Envfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def envfile_params
      params.require(:envfile).permit(:filename, :namespace_id, :filetype, :deleted_at)
    end
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  def index
    render json: {
      results: Namespace.distinct(:environment).pluck(:environment).map do |environment|
        {
          name: environment,
          value: environment,
          text: environment,
          disabled: false
        }
      end
    }
  end
end

app/controllers/namespaces_controller.rb
class NamespacesController < ApplicationController
  before_action :set_namespace, only: [:show, :edit, :update, :destroy]

  # GET /namespaces
  # GET /namespaces.json
  def index
    @namespaces = Namespace.all
  end

  # GET /namespaces/1
  # GET /namespaces/1.json
  def show
  end

  # GET /namespaces/new
  def new
    @namespace = Namespace.new
  end

  # GET /namespaces/1/edit
  def edit
  end

  # POST /namespaces
  # POST /namespaces.json
  def create
    @namespace = Namespace.new(namespace_params)

    respond_to do |format|
      if @namespace.save
        format.html { redirect_to @namespace, notice: 'Namespace was successfully created.' }
        format.json { render :show, status: :created, location: @namespace }
      else
        format.html { render :new }
        format.json { render json: @namespace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /namespaces/1
  # PATCH/PUT /namespaces/1.json
  def update
    respond_to do |format|
      if @namespace.update(namespace_params)
        format.html { redirect_to @namespace, notice: 'Namespace was successfully updated.' }
        format.json { render :show, status: :ok, location: @namespace }
      else
        format.html { render :edit }
        format.json { render json: @namespace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /namespaces/1
  # DELETE /namespaces/1.json
  def destroy
    @namespace.destroy
    respond_to do |format|
      format.html { redirect_to namespaces_url, notice: 'Namespace was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_namespace
      @namespace = Namespace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def namespace_params
      params.require(:namespace).permit(:team, :application, :environment, :deleted_at)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    render json: {
      results: Namespace.distinct(:team).pluck(:team).map do |team|
        {
          name: team,
          value: team,
          text: team,
          disabled: false
        }
      end
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/envfiles_helper.rb
module EnvfilesHelper
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/helpers/namespaces_helper.rb
module NamespacesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/applications/index.html.erb
<h1>Applications#index</h1>
<p>Find me in app/views/applications/index.html.erb</p>

app/views/envfiles/_form.html.erb
<%= form_with(model: envfile, local: true) do |form| %>
  <% if envfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(envfile.errors.count, "error") %> prohibited this envfile from being saved:</h2>

      <ul>
      <% envfile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :filename %>
    <%= form.text_field :filename %>
  </div>

  <div class="field">
    <%= form.label :namespace_id %>
    <%= form.text_field :namespace_id %>
  </div>

  <div class="field">
    <%= form.label :filetype %>
    <%= form.number_field :filetype %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/envfiles/edit.html.erb
<h1>Editing Envfile</h1>

<%= render 'form', envfile: @envfile %>

<%= link_to 'Show', @envfile %> |
<%= link_to 'Back', envfiles_path %>

app/views/envfiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Envfiles</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Namespace</th>
      <th>Filetype</th>
      <th>Deleted at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @envfiles.each do |envfile| %>
      <tr>
        <td><%= envfile.filename %></td>
        <td><%= envfile.namespace %></td>
        <td><%= envfile.filetype %></td>
        <td><%= envfile.deleted_at %></td>
        <td><%= link_to 'Show', envfile %></td>
        <td><%= link_to 'Edit', edit_envfile_path(envfile) %></td>
        <td><%= link_to 'Destroy', envfile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Envfile', new_envfile_path %>

app/views/envfiles/new.html.erb
<h1>New Envfile</h1>

<%= render 'form', envfile: @envfile %>

<%= link_to 'Back', envfiles_path %>

app/views/envfiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @envfile.filename %>
</p>

<p>
  <strong>Namespace:</strong>
  <%= @envfile.namespace %>
</p>

<p>
  <strong>Filetype:</strong>
  <%= @envfile.filetype %>
</p>

<p>
  <strong>File:</strong>
  <pre>
<%= @envfile.file.download if @envfile.file.attached? %>
  </pre>
</p>

<%= link_to 'Edit', edit_envfile_path(@envfile) %> |
<%= link_to 'Back', envfiles_path %>

app/views/environments/index.html.erb
<h1>Environments#index</h1>
<p>Find me in app/views/environments/index.html.erb</p>

app/views/layouts/_header.html.erb
<div class="computer tablet only row">
  <div class="ui inverted fixed menu navbar page grid">
    <%= link_to 'Config Site', root_path, class: 'brand item' %>

    <div id='team_select' class="ui dropdown selection item">
      <input type="hidden" name="gender">
      <i class="dropdown icon"></i>
      <div class="default text">Team</div>
      <div class="menu">
      </div>
    </div>

    <div id='application_select' class="ui dropdown selection item">
      <input type="hidden" name="gender">
      <i class="dropdown icon"></i>
      <div class="default text">Application</div>
      <div class="menu">
      </div>
    </div>

    <div id='environment_select' class="ui dropdown selection item">
      <input type="hidden" name="gender">
      <i class="dropdown icon"></i>
      <div class="default text">Environment</div>
      <div class="menu">
      </div>
    </div>

    <script>
      $('#team_select').dropdown({
          clearable: true,
          placeholder: 'Team',
          apiSettings: {
            url: '/teams/'
          },
          filterRemoteData: true
        });
      $('#application_select').dropdown({
          clearable: true,
          placeholder: 'Application',
          apiSettings: {
            url: '/applications/'
          },
          filterRemoteData: true
        });
      $('#environment_select').dropdown({
          clearable: true,
          placeholder: 'Environment',
          apiSettings: {
            url: '/environments/'
          },
          filterRemoteData: true
        });
    </script>

    <!--
      <%= link_to 'Home', root_path, class: 'active item' %>
      <%= link_to 'Namespaces', namespaces_path, class: 'item' %>
      <%= link_to 'Envfiles', envfiles_path, class: 'item' %>
      <a class="ui dropdown item">Dropdown
      <i class="dropdown icon"></i>
      <div class="menu">
      <div class="item">Action</div>
      <div class="item">Another action</div>
      <div class="item">Something else here</div>
      <div class="ui divider"></div>
      <div class="item">Seperated link</div>
      <div class="item">One more seperated link</div>
      </div>
      </a>
    -->
    <div class="right menu">
      <a id='clear_button' class="ui item">
        Clear
      </a>
      <script>
        $('#clear_button')
          .on('click', function() {
            $('.ui.dropdown')
              .dropdown('clear')
            ;
          });
      </script>
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'item') %>
      <% else %>
        <%= link_to('Login', new_user_session_path, class: 'item') %>
      <% end %>
    </div>
  </div>
</div>
<div class="mobile only row">
  <div class="ui fixed inverted navbar menu">
    <%= link_to 'Config Site', '/', class: 'brand item' %>
    <a href="" class="brand item">DB Config</a>
    <div class="right menu open">
      <a href="" class="menu item">
        <i class="reorder icon"></i>
      </a>
    </div>
  </div>
  <div class="ui vertical navbar menu">
    <!--
      <%= link_to 'Home', '/', class: 'active item' %>
      <%= link_to 'Namespaces', namespaces_path, class: 'item' %>
      <%= link_to 'Envfiles', envfiles_path, class: 'item' %>
      <div class="ui item">
      <div class="text">Dropdown</div>
      <div class="menu">
      <a class="item">Action</a>
      <a class="item">Another action</a>
      <a class="item">Something else here</a>
      <a class="ui aider"></a>
      <a class="item">Seperated link</a>
      <a class="item">One more seperated link</a>
      </div>
      </div>
    -->
    <div class="menu">
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'item') %>
      <% else %>
        <%= link_to('Login', new_user_session_path, class: 'item') %>
      <% end %>
    </div>
  </div>
</div>

<!--
  <div class="ui inverted left fixed vertical menu">
  <div class="active item"> 
  <%= link_to 'Home', '/' %>
  </div>
  <div class="item"> 
  <%= link_to 'Namespaces', namespaces_path %>
  </div>
  <div class="item"> 
  <%= link_to 'Envfiles', envfiles_path %>
  </div>
  <div class="right menu">
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'right item') %>
  <% else %>
    <%= link_to('Login', new_user_session_path, class: 'right item') %>
  <% end %>
  </div>
  </div>

  <div class="ui fixed inverted main menu">
  <div class="ui container">
  <a class="launch icon item">
  <i class="content icon"></i>
  </a>

  <div class="item">
  Menu
  </div>

  <div class="right menu">

  <div class="vertically fitted borderless item">
  <iframe class="github" src="//ghbtns.com/github-btn.html?user=semantic-org&amp;repo=semantic-ui&amp;type=watch&amp;count=true" allowtransparency="true" frameborder="0" scrolling="0" width="100" height="20"></iframe>
  </div>

  <div class="item">
  <div class="ui hidden right aligned search input" id="search">
  <div class="ui transparent icon input">
  <input class="prompt" type="text" placeholder="Search...">
  <i class="inverted search link icon" data-content="Search UI"></i>
  </div>
  <div class="results"></div>
  </div>
  </div>
  </div>
  </div>
  </div>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConfigPrototype</title>
    <%# Gon::Base.render_data %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag "pages/#{params[:controller]}/#{params[:action]}" %>
  </head>

  <body>
    <div class="ui grid">
      <%= render 'layouts/header' %>
    </div>
    <div class="ui page grid main">
      <%= yield %>
    </div>

    <%# if user_signed_in? %>
      <h1>
        <%# link_to('Logout', destroy_user_session_path, method: :delete) %>
      </h1>
    <%# end %>
    <!-- http://codkal.com/rails-how-to-remove-turbolinks/
      <%= link_to('Home', root_path) %> <br/>
      <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path) %>
        </li>
      <% end %>

      <div data-turbolinks="false">
        <a href="/">Turbolinks disabled</a>
        <a href="/" data-turbolinks="true">Turbolinks enabled</a>
        <a href="/">Disabled again</a>
      </div>
      <script>
        // GOOD WITH TURBOLINKS
        $(document).on('turbolinks:load', function () {
          console.log("This will run when dom is loaded!");
        });
      </script>
    -->
  </body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConfigPrototype</title>
    <%# Gon::Base.render_data %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag "pages/#{params[:controller]}/#{params[:action]}" %>

    <style>
      body {
        background-color: #ECF0F1;
      }

      .page-login {
        margin-top: 25px;
      }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/namespaces/_form.html.erb
<%= form_with(model: namespace, local: true) do |form| %>
  <% if namespace.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(namespace.errors.count, "error") %> prohibited this namespace from being saved:</h2>

      <ul>
      <% namespace.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team %>
    <%= form.text_field :team %>
  </div>

  <div class="field">
    <%= form.label :application %>
    <%= form.text_field :application %>
  </div>

  <div class="field">
    <%= form.label :environment %>
    <%= form.text_field :environment %>
  </div>

  <div class="field">
    <%# form.label :deleted_at %>
    <%# form.datetime_select :deleted_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/namespaces/edit.html.erb
<h1>Editing Namespace</h1>

<%= render 'form', namespace: @namespace %>

<%= link_to 'Show', @namespace %> |
<%= link_to 'Back', namespaces_path %>

app/views/namespaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Namespaces</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Application</th>
      <th>Environment</th>
      <th>Deleted at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @namespaces.each do |namespace| %>
      <tr>
        <td><%= namespace.team %></td>
        <td><%= namespace.application %></td>
        <td><%= namespace.environment %></td>
        <td><%= namespace.deleted_at %></td>
        <td><%= link_to 'Show', namespace %></td>
        <td><%= link_to 'Edit', edit_namespace_path(namespace) %></td>
        <td><%= link_to 'Destroy', namespace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Namespace', new_namespace_path %>

app/views/namespaces/new.html.erb
<h1>New Namespace</h1>

<%= render 'form', namespace: @namespace %>

<%= link_to 'Back', namespaces_path %>

app/views/namespaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @namespace.team %>
</p>

<p>
  <strong>Application:</strong>
  <%= @namespace.application %>
</p>

<p>
  <strong>Environment:</strong>
  <%= @namespace.environment %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @namespace.deleted_at %>
</p>

<%= link_to 'Edit', edit_namespace_path(@namespace) %> |
<%= link_to 'Back', namespaces_path %>